<script>
    require([
        "jquery",
        "Magento_Ui/js/modal/modal",
        'mage/backend/notification',
        "prototype"
    ], function (jQuery, modal, notification) {

//<![CDATA[
        Window.keepMultiModalWindow = true;
        var reporterGenerateModal = {
            overlayShowEffectOptions: null,
            overlayHideEffectOptions: null,
            modal: null,
            open: function (viewUrl, elementId) {
                if (viewUrl && elementId) {
                    jQuery.ajax({
                        url: viewUrl,
                        data: {
                            id: elementId
                        },
                        showLoader: true,
                        dataType: 'html',
                        success: function (data, textStatus, transport) {
                            this.openDialogWindow(data, elementId);
                        }.bind(this)
                    });
                }
            },
            openDialogWindow: function (data, elementId) {
                var self = this;
                if (this.modal) {
                    this.modal.html(jQuery(data).html());
                } else {
                    this.modal = jQuery(data).modal({
                        title: '<?= /* @escapeNotVerified */ __('Generate Report'); ?>',
                        modalClass: 'magento',
                        type: 'slide',
                        firedElementId: elementId,
                        buttons: [
                            {
                                text: jQuery.mage.__('Close'),
                                class: 'action- scalable back',
                                click: function () {
                                    self.closeDialogWindow(this);
                                }
                            },
                            {
                                text: jQuery.mage.__('Generate & Download'),
                                class: 'action-primary ',
                                click: function () {
                                    jQuery('body').trigger('processStart');

                                    setTimeout(function () {
                                        jQuery('body').trigger('processStop');
                                    }, 2500)
                                }
                            }
                        ],
                        close: function () {
                            self.closeDialogWindow(this);
                        }
                    });
                }
                this.modal.modal('openModal');
            },
            closeDialogWindow: function (dialogWindow) {
                jQuery('body').trigger('processStop');
                dialogWindow.closeModal();
                Windows.overlayShowEffectOptions = this.overlayShowEffectOptions;
                Windows.overlayHideEffectOptions = this.overlayHideEffectOptions;
            }
        };

        window.reporterGenerateModal = reporterGenerateModal;
//]]>
    });
</script>
